# you may replace the default AlgebraicJulia pipeline with your own. Just move
# your pipeline into the .buildkite directory and rename the file being checked
# below to your pipeline. More documentation to come.
steps:

  # load the 
  - label: ":arrow_down: Load AlgebraicJulia pipeline"
    command: |
      if [ -f ".buildkite/example.yml.bak" ]; then
        buildkite-agent pipeline upload .buildkite/example.yml
      else
        curl -s https://raw.githubusercontent.com/AlgebraicJulia/.github/main/buildkite/pipeline.yml | buildkite-agent pipeline upload
      fi

  - label: ":racehorse: Build docs and run tests on {{matrix.name}} partition"
    command:
      - "srun --cpus-per-task=16 --mem=16G  --gres=gpu:{{matrix.gpu}} --time=1:00:00 -p gpu --output=.buildkite/gpu_{{matrix.gpu}}_%j.log --unbuffered .buildkite/jobscript.sh"
    matrix:
      adjustments:
        - with:
            name: "A100 GPU"
            gpu: "a100"
        - with:
            name: "Quadro"
            gpu: "geforce"

  - wait
