# you may replace the default AlgebraicJulia pipeline with your own. Just move
# your pipeline into the .buildkite directory and rename the file being checked
# below to your pipeline. More documentation to come.
steps:

  - label: ":arrow_down: Load AlgebraicJulia pipeline"
    command: |
      if [ -f ".buildkite/example.yml.bak" ]; then
        buildkite-agent pipeline upload .buildkite/example.yml
      else
        curl -s https://raw.githubusercontent.com/AlgebraicJulia/.github/main/buildkite/pipeline.yml | buildkite-agent pipeline upload
      fi

  - label: ":racehorse: Build docs and run tests on A100 GPU partition"
    command:
      - "srun --cpus-per-task=16 --mem=16G  --gres=gpu:a100:1 --time=1:00:00 -p gpu --output=.buildkite/log_gpu_a100_%j.log --unbuffered .buildkite/jobscript.sh"

  - label: ":racehorse: Build docs and run tests on Quadro GPU partition"
    command:
      - "srun --cpus-per-task=16 --mem=16G  --gres=gpu:geforce:1 --time=1:00:00 -p gpu --output=.buildkite/log_gpu_quadro_%j.log --unbuffered .buildkite/jobscript.sh"

  - wait
